# Table Question Answering

![JohnSnowLabs](https://nlp.johnsnowlabs.com/assets/images/logo.png)
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/JohnSnowLabs/nlu/blob/master/examples/colab/component_examples/table_question_answering/table_question_answering_with_tapas.ipynb)

## TAPAS

TapasForQuestionAnswering can load TAPAS Models with a cell selection head and optional aggregation head on top for question-answering tasks on tables (linear layers on top of the hidden-states output to compute logits and optional logits_aggregation), e.g. for SQA, WTQ or WikiSQL-supervised tasks. TAPAS is a BERT-based model specifically designed (and pre-trained) for answering questions about tabular data.


[TAPAS: Weakly Supervised Table Parsing via Pre-training](https://aclanthology.org/2020.acl-main.398.pdf)

![TAPAS](https://user-images.githubusercontent.com/5762953/192140733-e08a1e99-0aee-455d-af29-73af497a03ef.png)

In [ ]:
%%capture
! pip install nlu
! pip install pyspark==3.1.1

In [ ]:
import pandas as pd 

# First we need a pandas dataframe on for which we want to ask questions. The so called "context"
context_df = pd.DataFrame({
    'name':['Donald Trump','Elon Musk'], 
    'money': ['$100,000,000','$20,000,000,000,000'], 
    'married': ['yes','no'], 
    'age' : ['75','55'] })
context_df

           name                money married age
0  Donald Trump         $100,000,000     yes  75
1     Elon Musk  $20,000,000,000,000      no  55

In [ ]:
# Then we create an array of questions
questions = [
    "Who earns less than 200,000,000?",
    "Who earns more than 200,000,000?",
    "Who earns 100,000,000?",
    "How much money has Donald Trump?",
    "Who is the youngest?",
]
questions

['Who earns less than 200,000,000?',
 'Who earns more than 200,000,000?',
 'Who earns 100,000,000?',
 'How much money has Donald Trump?',
 'Who is the youngest?']

In [ ]:
# Now we combine both to a tuple and we are done! We can now pass this to the .predict() method
tapas_data = (context_df, questions)
tapas_data

(           name                money married age
 0  Donald Trump         $100,000,000     yes  75
 1     Elon Musk  $20,000,000,000,000      no  55,
 ['Who earns less than 200,000,000?',
  'Who earns more than 200,000,000?',
  'Who earns 100,000,000?',
  'How much money has Donald Trump?',
  'Who is the youngest?'])

In [ ]:
import nlu
# Lets load a TAPAS QA model and predict on (context,question) 
tapas = nlu.load('en.answer_question.tapas.wtq.large_finetuned')

# It will give us an aswer for every question in the questions array,
# based on the context in context_df
answers = tapas.predict(tapas_data)
answers

Warning::Spark Session already created, some configs may not take.
Warning::Spark Session already created, some configs may not take.
table_qa_tapas_large_finetuned_wtq download started this may take some time.
Approximate size to download 1.2 GB
[OK!]
sentence_detector_dl download started this may take some time.
Approximate size to download 354.6 KB
[OK!]
Warning::Spark Session already created, some configs may not take.

,sentence,tapas_qa_UNIQUE_aggregation,tapas_qa_UNIQUE_answer,tapas_qa_UNIQUE_cell_positions,tapas_qa_UNIQUE_cell_scores,tapas_qa_UNIQUE_origin_question,text
0,"Who earns less than 200,000,000?",NONE,Donald Trump,"[0, 0]",1.0,"Who earns less than 200,000,000?","{""header"":[""name"",""money"",""married"",""age""],""ro..."
0,"Who earns more than 200,000,000?",NONE,Elon Musk,"[0, 1]",1.0,"Who earns more than 200,000,000?","{""header"":[""name"",""money"",""married"",""age""],""ro..."
0,"Who earns 100,000,000?",NONE,Donald Trump,"[0, 0]",1.0,"Who earns 100,000,000?","{""header"":[""name"",""money"",""married"",""age""],""ro..."
0,How much money has Donald Trump?,SUM,"SUM($100,000,000)","[1, 0]",1.0,How much money has Donald Trump?,"{""header"":[""name"",""money"",""married"",""age""],""ro..."
0,Who is the youngest?,NONE,Elon Musk,"[0, 1]",1.0,Who is the youngest?,"{""header"":[""name"",""money"",""married"",""age""],""ro..."

## Try out other models

 There are many more TAPAS models for question answering

 You can try any of them out by simply chaning the parameter of `nlu.load('my_model')` to the one you want to test.


Refer to the [modelshub](https://nlp.johnsnowlabs.com/models?task=Table+Question+Answering) for the full list



| Language   | NLU Reference                                                                                                                                           | Spark NLP  Reference                                                                                                                                     | Annotator Class           |
|:-----------|:--------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------|
| en         | [en.answer_question.tapas](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_table_question_answering_tapas_en.html)                                     | [table_qa_table_question_answering_tapas](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_table_question_answering_tapas_en.html)                       | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.by_uploaded by huggingface](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_temporary_repo_en.html)                    | [table_qa_tapas_temporary_repo](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_temporary_repo_en.html)                                           | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.sqa.base_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_base_finetuned_sqa_en.html)                        | [table_qa_tapas_base_finetuned_sqa](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_base_finetuned_sqa_en.html)                                   | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.sqa.large_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_large_finetuned_sqa_en.html)                      | [table_qa_tapas_large_finetuned_sqa](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_large_finetuned_sqa_en.html)                                 | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.sqa.medium_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_medium_finetuned_sqa_en.html)                    | [table_qa_tapas_medium_finetuned_sqa](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_medium_finetuned_sqa_en.html)                               | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.sqa.mini_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_mini_finetuned_sqa_en.html)                        | [table_qa_tapas_mini_finetuned_sqa](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_mini_finetuned_sqa_en.html)                                   | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.sqa.small_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_small_finetuned_sqa_en.html)                      | [table_qa_tapas_small_finetuned_sqa](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_small_finetuned_sqa_en.html)                                 | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.sqa.tiny_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_tiny_finetuned_sqa_en.html)                        | [table_qa_tapas_tiny_finetuned_sqa](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_tiny_finetuned_sqa_en.html)                                   | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wikisql.base_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_base_finetuned_wikisql_supervised_en.html)     | [table_qa_tapas_base_finetuned_wikisql_supervised](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_base_finetuned_wikisql_supervised_en.html)     | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wikisql.large_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_large_finetuned_wikisql_supervised_en.html)   | [table_qa_tapas_large_finetuned_wikisql_supervised](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_large_finetuned_wikisql_supervised_en.html)   | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wikisql.medium_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_medium_finetuned_wikisql_supervised_en.html) | [table_qa_tapas_medium_finetuned_wikisql_supervised](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_medium_finetuned_wikisql_supervised_en.html) | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wikisql.small_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_small_finetuned_wikisql_supervised_en.html)   | [table_qa_tapas_small_finetuned_wikisql_supervised](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_small_finetuned_wikisql_supervised_en.html)   | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wtq.large_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_large_finetuned_wtq_en.html)                      | [table_qa_tapas_large_finetuned_wtq](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_large_finetuned_wtq_en.html)                                 | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wtq.medium_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_medium_finetuned_wtq_en.html)                    | [table_qa_tapas_medium_finetuned_wtq](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_medium_finetuned_wtq_en.html)                               | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wtq.mini_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_mini_finetuned_wtq_en.html)                        | [table_qa_tapas_mini_finetuned_wtq](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_mini_finetuned_wtq_en.html)                                   | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wtq.small_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_small_finetuned_wtq_en.html)                      | [table_qa_tapas_small_finetuned_wtq](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_small_finetuned_wtq_en.html)                                 | TapasForQuestionAnswering |
| en         | [en.answer_question.tapas.wtq.tiny_finetuned](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_tiny_finetuned_wtq_en.html)                        | [table_qa_tapas_tiny_finetuned_wtq](https://nlp.johnsnowlabs.com/2022/09/30/table_qa_tapas_tiny_finetuned_wtq_en.html)                                   | TapasForQuestionAnswering |